<?php
/**
 * ShippingInfoTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FormsmedjanKlarnaOrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FormsmedjanKlarnaOrderManagement\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShippingInfoTest Class Doc Comment
 *
 * @category    Class
 * @description ShippingInfo
 * @package     FormsmedjanKlarnaOrderManagement
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShippingInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShippingInfo"
     */
    public function testShippingInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipping_company"
     */
    public function testPropertyShippingCompany()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipping_method"
     */
    public function testPropertyShippingMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tracking_uri"
     */
    public function testPropertyTrackingUri()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "return_shipping_company"
     */
    public function testPropertyReturnShippingCompany()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "return_tracking_number"
     */
    public function testPropertyReturnTrackingNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "return_tracking_uri"
     */
    public function testPropertyReturnTrackingUri()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
