<?php
/**
 * CapturesApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  FormsmedjanKlarnaOrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FormsmedjanKlarnaOrderManagement\Test\Api;

use \FormsmedjanKlarnaOrderManagement\Configuration;
use \FormsmedjanKlarnaOrderManagement\ApiException;
use \FormsmedjanKlarnaOrderManagement\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CapturesApiTest Class Doc Comment
 *
 * @category Class
 * @package  FormsmedjanKlarnaOrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CapturesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for appendShippingInfo
     *
     * Add shipping info to a capture.
     *
     */
    public function testAppendShippingInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for captureOrder
     *
     * Create capture.
     *
     */
    public function testCaptureOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for extendDueDate
     *
     * Extend the customer's payment due date.
     *
     */
    public function testExtendDueDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCapture
     *
     * Get capture.
     *
     */
    public function testGetCapture()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCaptures
     *
     * Get all captures for one order.
     *
     */
    public function testGetCaptures()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOptionsForExtendDueDate
     *
     * Get available options for extension of the customer's payment due date.
     *
     */
    public function testGetOptionsForExtendDueDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for triggerSendOut
     *
     * Trigger resend of customer communication.
     *
     */
    public function testTriggerSendOut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
