<?php
/**
 * RefundsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  FormsmedjanKlarnaOrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FormsmedjanKlarnaOrderManagement\Test\Api;

use \FormsmedjanKlarnaOrderManagement\Configuration;
use \FormsmedjanKlarnaOrderManagement\ApiException;
use \FormsmedjanKlarnaOrderManagement\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RefundsApiTest Class Doc Comment
 *
 * @category Class
 * @package  FormsmedjanKlarnaOrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RefundsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for get
     *
     * Get refund.
     *
     */
    public function testGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for refundOrder
     *
     * Create a refund.
     *
     */
    public function testRefundOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
